/* La tabla de textos. Ver ssbtext.h para el porque de que este aqui. */
#include "ssbgui.h"

const char_t *const SSB_TEXT[LANG_COUNT][TXT_COUNT] = {
    /* ---------------------------------------------------------- ingles */
    {
        "Add track",
        "Remove",
        "Record",
        "Stop",
        "Freeze",
        "Resume",
        "Live",
        "All",
        "Save as...",
        "Buffer:",
        "Storage:",
        "Export:",
        "Lossless 16-bit",
        "Raw 16-bit",
        "Lossless 24-bit",
        "Raw 24-bit",
        "+",
        "-",
        "Folder...",
        "Default",
        "Small",
        "Full",
        "Commands",
        "No commands",
        "Command mode. Type help and press Enter.",
        "ES",
        "SystemSoundBuffer",

        "Drag to select   |   wheel = scroll   |   Ctrl+wheel = zoom   |   M mutes, X closes   |   F1 = keyboard commands",
        "Pick a source above and press Add track.",
        "%u track(s)   buffer %.1f s   disk %.1f MB   compression x%.1f   window %.1f s%s",
        "Selection: %.2f s   (ends %.1f s ago)",
        "REC",
        "READY - press Record to start",
        "STOPPED",
        "VIEW FROZEN",
        "MUTED",
        "SYSTEM OUTPUT IS MUTED - this track is recording silence",
        "no signal",
        "THIS SOURCE IS GONE - the device or app is no longer there",
        "Keyboard commands   (F1)",
        "record or stop",
        "play or pause the selection",
        "stop playback",
        "select everything",
        "save the selection",
        "one file / separate files",
        "destination folder",
        "freeze the view",
        "back to live",
        "compact mode",
        "typed command console",
        "show or hide this list",

        "Stopped. The buffers stay as they are.",
        "Recording.",
        "Drag over the waveform to select a range.",
        "Saved %u of %u tracks, %.2f s each: %s-N.%s",
        "Mixed %u tracks into one file, %.2f s: %s.%s   (gain x%.3f)",
        "Could not open the audio device to play.",
        "Play",
        "Pause",
        "Resume",
        "One file",
        "Separate files",
        "Saved as WAV: the system could not encode to %s.",
        "Tracks run at different sample rates, so they cannot go into one file. Saved %u separate files instead: %s-N.%s",
        "Could not mix the tracks into one file (%s).",
        "That selection falls outside what every track covers.",
        "Could not open that source.",
        "Every track is muted: nothing to save.",
        "Track %u muted.",
        "Track %u unmuted.",
        "Saving to: %s",
        "Buffer set to %s on every track.",
        "Save the selection",

        "Ctrl+P. Starts and stops recording on every track. Stopped, the buffers stay untouched so you can look and save without losing anything",
        "Ctrl+E. Freezes the view only; capture keeps running",
        "Applies to tracks added from now on",
        "Lossless is exact, byte for byte. It has nothing to do with the frames a source may drop",
        "File format for the saved selection. MP3 and AAC use the encoder that ships with the system",
        "Switch language",
        "Folder where Ctrl+S saves the selection",
    },
    /* --------------------------------------------------------- espanol */
    {
        "Anadir pista",
        "Quitar",
        "Grabar",
        "Parar",
        "Congelar",
        "Continuar",
        "Directo",
        "Todo",
        "Guardar...",
        "Buffer:",
        "Almacenamiento:",
        "Exportar:",
        "Sin perdida 16 bits",
        "Crudo 16 bits",
        "Sin perdida 24 bits",
        "Crudo 24 bits",
        "+",
        "-",
        "Carpeta...",
        "Por omision",
        "Reducido",
        "Completo",
        "Comandos",
        "Sin comandos",
        "Modo comandos. Escribe help y pulsa Enter.",
        "EN",
        "SystemSoundBuffer",

        "Arrastra para seleccionar   |   rueda = scroll   |   Ctrl+rueda = zoom   |   M silencia, X cierra   |   F1 = comandos de teclado",
        "Elige una fuente arriba y pulsa Anadir pista.",
        "%u pista(s)   buffer %.1f s   disco %.1f MB   compresion x%.1f   ventana %.1f s%s",
        "Seleccion: %.2f s   (termina hace %.1f s)",
        "REC",
        "LISTO - pulsa Grabar para empezar",
        "PARADO",
        "VISTA CONGELADA",
        "SILENCIADA",
        "LA SALIDA DEL SISTEMA ESTA MUDA - esta pista graba silencio",
        "sin senal",
        "ESTA FUENTE YA NO ESTA - el dispositivo o la aplicacion han desaparecido",
        "Comandos de teclado   (F1)",
        "grabar o parar",
        "reproducir o pausar la seleccion",
        "parar la reproduccion",
        "seleccionar todo",
        "guardar la seleccion",
        "un fichero / ficheros aparte",
        "carpeta de destino",
        "congelar la vista",
        "volver al directo",
        "modo reducido",
        "consola de comandos escritos",
        "mostrar u ocultar esta lista",

        "Parado. Los buffers se quedan como estan.",
        "Grabando.",
        "Arrastra sobre la onda para seleccionar un tramo.",
        "Guardadas %u de %u pistas, %.2f s cada una: %s-N.%s",
        "Mezcladas %u pistas en un fichero, %.2f s: %s.%s   (ganancia x%.3f)",
        "No se pudo abrir el dispositivo de audio para reproducir.",
        "Reproducir",
        "Pausa",
        "Seguir",
        "Un fichero",
        "Ficheros aparte",
        "Guardado en WAV: el sistema no pudo codificar a %s.",
        "Las pistas van a frecuencias distintas y no caben en un solo fichero. Se han guardado %u ficheros por separado: %s-N.%s",
        "No se han podido juntar las pistas en un fichero (%s).",
        "Esa seleccion cae fuera de lo que cubren todas las pistas.",
        "No se pudo abrir esa fuente.",
        "Todas las pistas estan silenciadas: no hay nada que guardar.",
        "Pista %u silenciada.",
        "Pista %u activada.",
        "Se guarda en: %s",
        "Buffer puesto a %s en todas las pistas.",
        "Guardar la seleccion",

        "Ctrl+P. Arranca y para la grabacion de todas las pistas. Parado, los buffers quedan intactos para mirar y guardar sin perder nada",
        "Ctrl+E. Congela solo la vista; la captura sigue",
        "Se aplica a las pistas que se anadan a partir de ahora",
        "Sin perdida es exacto, byte a byte. No tiene nada que ver con los frames que pueda perder una fuente",
        "Formato del fichero que se guarda. MP3 y AAC usan el codificador que trae el sistema",
        "Cambiar de idioma",
        "Carpeta donde Ctrl+S guarda la seleccion",
    }
};
